version: '3.1'
services:
  lb:
    image: traefik:latest
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --docker
    networks:
      - back
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
  geth:
    image: ethereum/client-go
    volumes:
      - ./geth.toml:/etc/geth.toml
    command:
      - --config
      - /etc/geth.toml
    networks:
      - back
    restart: unless-stopped
    labels:
      traefik.frontend.entryPoints: ${ENTRYPOINT}
      traefik.frontend.rule: ${FRONTEND_RULE}
      traefik.port: "8545"
networks:
  back: